### PR TITLE
Update documentation/screenshots

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2210

# What does this Pull Request do?

Adds Ghostscript as an optional dependency. Remove references to **books** as this works for **newspapers** to, so make generic. Add new screenshot.

# What's new?
New screenshot with Solr options expanded.

# How should this be tested?

View, compare, comment.

# Additional Notes:

Example:
* Does this change require documentation to be updated? This is documentation
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by rosiel — COMMENTED** [review]
Nice screenshot! Uh... it makes me wonder why "Use solr to derive pages and sequence numbers" requires solr fields for the height and width, but not for isPageOf or sequence numbers. Should that be documented here?

**Comment by whikloj** [comment]
It does, but that field (**Solr page sequence number field**) is outside that grouping.
I'm guessing that the reason for that is because it is also used for [highlighting](https://github.com/Islandora/islandora_paged_content/blob/3a46a57f14fd69ceeee386dad665b925bcbc757b/includes/highlighting.inc#L25)

**Comment by whikloj** [comment]
Bump

**Review by rosiel — APPROVED** [review]

**Comment by DiegoPino** [comment]
@rosiel kind reminder to merge =)

**Pull request merged**
