### PR TITLE
Update License to standard form

### PR DESCRIPTION
**Pull request by DiegoPino**
Release 7.x-1.9 Audit

# What does this Pull Request do?

Updates Licence to standard format from https://www.gnu.org/licenses/gpl-3.0.txt

# Interested parties
@manez @willtp87  or any @Islandora/7-x-1-x-committers willing to help.

### CODE REVIEW

**Review by willtp87 — APPROVED** [review]

**Comment by willtp87** [comment]
@manez I see many similar things being merged regardless of the 24h wait period. Please let me know if that is inappropriate in this case and I will submit a revert.

**Comment by DiegoPino** [comment]
@willtp87 i don't see any issues here and thanks for merging. But Since i'm the one pulling, i guess i'm not a good reference. This is work that sadly was on the Auditor's side and failed to be detected/fixed (we all failed maybe in asking them exactly what to do).

**Comment by manez** [comment]
@willtp87 since these updates to readme/licence files don't effect code but do cause headaches if they are not in for the code freeze, please do merge on a  shorter timeline. We've had previous corrections for this issue open for longer stretches, so I think there's been a reasonable amount of time for feedback on this update *in general* even if individual pulls are handled quickly today.

**Comment by manez** [comment]
er... with the usual caveat that we need to make sure there's a CLA, but since it's @DiegoPino doing the lion's share of the work, not an issue 😄

**Comment by DiegoPino** [comment]
@willtp87 have to say thanks again!

**Pull request merged**
